from pathlib import Path
import csv, json, math, zipfile

OUT = Path(__file__).resolve().parent
sources = []
def src(i,title,publisher,date,url,locator,fact,limit,access='PUBLIC_PRIMARY_TEXT'):
    sources.append(dict(SOURCE_ID=i,TITLE=title,PUBLISHER=publisher,PUBLICATION_DATE=date,URL=url,LOCATOR=locator,FACT_USED=fact,LIMITATIONS=limit,ACCESS_STATUS=access,REVIEW_DATE='2026-09-15'))

src('S01','2025 Wilpinjong technical report summary','Peabody / SEC','2026','https://www.sec.gov/Archives/edgar/data/1064728/000106472826000006/btu_20251231xex962.htm','Sections 16.2 and 16.4','AGL open-book supply agreement scheduled to finish in 2028; flexible nominations; remaining production exported.','No current AGL price or Bayswater blend percentage disclosed.')
src('S02','FY25 results presentation','AGL','2025-08-13','https://announcements.asx.com.au/asxpdf/20250813/pdf/06mtcw5jhkzf4t.pdf','Slide 33','Bayswater can use 4800 kcal/kg coal; additional FY26/27 supply discounted to Newcastle; legacy contracts roll off.','Capability is not actual average coal quality. Discounts do not disclose delivered price.')
src('S03','Annual Report 2025','AGL','2025-08-13','https://www.agl.com.au/content/dam/digital/agl/documents/about-agl/company-docs/250813-2-agl-energy-limited-annual-report-2025.pdf','Operating and financial review, p.24','FY25 coal fuel expense A$583m and about A$22/MWh across coal fleet.','Fleet total cannot uniquely identify Bayswater and Loy Yang unit prices.','PRIMARY_INDEXED_TEXT; large PDF not fully retrieved')
src('S04','FY26 half-year report','AGL','2026-02-11','https://www.agl.com.au/content/dam/digital/agl/documents/about-agl/news-centre/2026/260211-appendix-4d-and-fy26-half-year-report.pdf','Operating review, p.7','Coal fleet fuel expense A$289m, A$23.8/MWh; higher Bayswater coal costs.','Half-year fleet expense; no station coal price.')
src('S05','March 2026 quarterly report','Origin Energy','2026-04-27','https://announcements.asx.com.au/asxpdf/20260427/pdf/06ywbyxms9scmn.pdf','Commodity exposure, PDF p.28','Eraring 5.5-6 Mtpa; largely discounted Newcastle 6000 pricing and hedging. FY27 approximately 1Mt opening stock plus 3.6Mt contracted/hedged, 75-85% coverage.','Coverage excludes closing stockpile; neither mine mix nor derivative of delivered cost to export price.')
src('S06','Origin and Centennial agree supply from Myuna Colliery','Origin Energy','2026-03-03','https://www.originenergy.com.au/about/investors-media/origin-and-centennial-agree-supply-from-myuna-colliery/','Announcement','Final agreement supplies Myuna coal to December 2028; significant costs absorbed.','Final tariff and surcharge not published; direct page returned 404 during review.','PRIMARY_INDEXED_TEXT')
src('S07','Origin offers Myuna end-of-life coal supply agreement','Origin Energy','2026-02-05','https://www.originenergy.com.au/about/investors-media/origin-offers-myuna-end-of-life-coal-supply-agreement/','Negotiation announcement','A$50m/year relates to Centennial demand above market during negotiations.','Not evidence that the final March agreement adopted this exact premium.','PRIMARY_INDEXED_TEXT')
src('S08','Senate committee hearing, 23 April 2024','Australian Parliament','2024-04-23','https://www.aph.gov.au/Parliamentary_Business/Hansard/Hansard_Display?bid=committees%2Fcommsen%2F27922%2F&sid=0000','Evidence concerning Myuna','Myuna described as landlocked and supplying Eraring exclusively.','Does not establish Myuna share of Eraring total burn.')
src('S09','Mandalong operation','Centennial','undated','https://www.centennialcoal.com.au/operations/mandalong?page=1','Operation description','Mandalong supplies Eraring and Vales Point.','No current station allocation or price.')
src('S10','Investment in supply reliability following 2022','EnergyAustralia','2023','https://www.energyaustralia.com.au//about-us/media/news/energyaustralia-accelerates-investment-energy-supply-reliability-following-2022','Coal supply discussion','Mt Piper multi-mine agreement includes Airly and Springvale.','Agreement economics and current mine shares undisclosed.')
src('S11','2024 Management Discussion and Analysis','Banpu','2025-02','https://www.banpu.com/wp-content/uploads/2025/02/2024-Banpu-MDA-En.pdf','Australia domestic selling price discussion','2024 Australian domestic ASP excluding traded coal A$170.52/t, versus A$123.39/t in 2023.','Supplier-wide nominal ASP, not Mt Piper invoice or necessarily delivered basis; direct link returned 404.','PRIMARY_INDEXED_TEXT')
src('S12','Annual Report 2024','Banpu','2025-03-14','https://www.banpu.com/wp-content/uploads/2025/03/Banpu-One-Report-2024_EN_14-Mar-25.pdf','p.217','Australia domestic pricing increased with new contracts; corroborates S11.','Same underlying disclosure as S11, not independent evidence; direct download unavailable.','PRIMARY_INDEXED_TEXT')
src('S13','2025 Management Discussion and Analysis','Banpu','2026-02','https://www.banpu.com/wp-content/uploads/2026/02/2025-Banpu-MDA-En.pdf','Australia mining results','2025 Australian mixed-market ASP A$152.90/t and cost A$143.80/t.','Includes export business; cannot replace domestic ASP or station tariff.','PRIMARY_INDEXED_TEXT')
src('S14','Q1 2026 Management Discussion and Analysis','Banpu / Thai SEC','2026-05-12','https://market.sec.or.th/public/idisc/Download?FILEID=dat%2Fnews%2F202605%2F0148NWS120520260708158910E.pdf','Australia discussion, pp.9-10','Q1 2026 Australian mixed ASP A$153.89/t, cost A$152.57/t.','Mixed-market and mine-cost measures; not domestic delivered station prices.')
src('S15','Independent financial adviser opinion on amalgamation','Banpu Power / independent financial adviser','2026-01-07','https://www.banpupower.com/wp-content/uploads/2026/01/1313NWS070120261751295780E.pdf','Section 5 p.100; PDF p.200','BPA valuation used book-value approach; future Australian mine production/prices could not be estimated sufficiently for DCF.','Transaction opinion supplies no usable current station tariff.')
src('S16','2025 annual results analyst briefing transcript','CLP','2026-02-26','https://www.clpgroup.com/content/dam/clp-group/channels/investor/document/3-2-results---presentations/2025/CLP%20Holdings_2025%20Annual%20Results%20Analyst%20Briefing_Transcript.pdf.coredownload.pdf','Australia performance discussion','Higher Mt Piper coal costs noted.','Qualitative direction, not price/GJ.')
src('S17','Chain Valley Colliery consolidation project','Delta Electricity','undated','https://www.deltapae.com.au/operations/chain-valley-colliery/chain-valley-colliery-environment/consolidation-project','Project overview','Around 1.3Mt/year, approximately half of Vales Point coal requirements.','Approximate physical tonnage share; current energy share and component prices not disclosed.','PRIMARY_INDEXED_TEXT; direct access restricted')
src('S18','Chain Valley consolidation approved, limited to Vales Point','NSW Independent Planning Commission','2026-04','https://www.ipcn.nsw.gov.au/news/chain-valley-colliery-consolidation-project-approved-limited-supplying-vales-point-power','Decision summary','Extracted coal restricted to Vales Point; mine life to 31 December 2029.','Supply restriction does not set price or actual blend.')
src('S19','Chain Valley applicant meeting transcript','NSW Independent Planning Commission','2026-02-09','https://www.ipcn.nsw.gov.au/sites/default/files/2026-02/Chain%20Valley%20Colliery%20Consolidation%20Project_Applicant%20meeting%20transcript.pdf','p.8','Applicant explains Chain Valley is not always the cheapest coal source; logistics and security matter.','No numeric captive or external price disclosed.')
src('S20','2025 Form 10-K / annual report','Coronado Global Resources / SEC','2026','https://www.sec.gov/Archives/edgar/data/1770561/000110465926046838/tm264496d1_ars.pdf','Stanwell agreements and amendments; pp.17-19; related financing notes','Legacy thermal contract below supplier cost through 2025; 2025 amendments include prepayments, rebate changes and additional future tonnage.','Financing and deferred accounting are not a simple delivered coal tariff; supplier thermal/export mix is not station exposure.')
src('S21','December 2025 quarterly report','Coronado Global Resources / SEC','2026-01','https://www.sec.gov/Archives/edgar/data/1770561/000110465926007024/tm264164d1_ex99-1.htm','Stanwell coal supply agreement','Contract reset advanced into 2026.','No complete all-in station cost disclosed.')
src('S22','Q2 2026 Form 10-Q','Coronado Global Resources / SEC','2026','https://www.sec.gov/Archives/edgar/data/1770561/000156276226000094/Form10q2026q2.htm','Stanwell / NCSA and deferred right-to-mine discount discussion','NCSA timing expected in Q2 2027; continuing deferred contractual balances.','Update must be read with earlier amendments; does not support a timeless fixed-price assumption.')
src('S23','Meandu Mine','Stanwell','undated','https://www.stanwell.com/meandu-mine','Mine overview','Meandu exclusively supplies adjacent Tarong stations; 1.5km conveyor; capacity 7.6Mtpa.','Capacity is not actual annual output; no mine cost disclosed.')
src('S24','Golding awarded Stanwell Meandu Mine contract','NRW Holdings','2026-01-19','https://nrw.com.au/golding-awarded-stanwell-meandu-mine-contract/','Contract announcement','A$750m over 5.5 years; capital-light mining contract.','Contract revenue excludes some owner costs and is forward nominal money.')
src('S25','HY26 results presentation','NRW Holdings','2026-02-19','https://announcements.asx.com.au/asxpdf/20260219/pdf/06wgt7sqywy861.pdf','p.9','Meandu operational control July 2026; 100% client-owned fleet.','Owner fleet depreciation/capital cost not captured by contractor-only quotient.')
src('S26','Kogan Creek contract extension','NRW Holdings','2021-11-15','https://announcements.asx.com.au/asxpdf/20211115/pdf/452yzygjvz0n4n.pdf','Contract terms','A$150m four-year contract July 2022-June 2026, further four-year option; contractor provides major equipment.','Option exercise and current all-in owner cost not verified.')
src('S27','Kogan Creek Power Station','CS Energy','undated','https://www.csenergy.com.au/what-we-do/thermal-generation/kogan-creek-power-station','Fuel supply','Owned adjacent mine, coal supplied by conveyor.','Does not disclose delivered cost.')
src('S28','Annual Report 2022','CS Energy','2022','https://www.csenergy.com.au/ArticleDocuments/191/CS%20ENERGY%20ANNUAL%20REPORT%202022%20ONLINE.pdf.aspx','p.25','Long-term coal arrangements insulated from international price movements; Kogan captive and Callide non-market-linked.','Historical contract description; later amendments must be checked.')
src('S29','Our Jim & Felicja Superfund v Lindenfels [2026] FCA 307','Federal Court, reproduced by Changeflow','2026-03-20','https://changeflow.com/govping/courts-legal/shareholder-oppression-claim-dismissed-20th-mar-2026-04-02','Paragraphs 153 and 159-160','2016 transaction context: approximate A$27/t domestic coal, mandatory CSE 2.4Mtpa to 2032 and CPM 3Mtpa to 2033; domestic priority.','Historical price, not current invoice. Indexed reproduction; official court endpoint restricted and mirror direct link returned 410. Treat as historical research lead with access limitation.','INDEXED_JUDGMENT_REPRODUCTION')
src('S30','Oppression is not unlawfulness','Johnson Winter Slattery','2026-05-26','https://jws.com.au/what-we-think/oppression-is-not-unlawfulness-federal-court-reinforces-boundary-between-breach-of-duty-and-statutory-oppression/','Case discussion','Confirms identity and outcome of FCA 307 litigation concerning Batchfire.','Lawyer commentary corroborates case, not independently the A$27/t passage.')
src('S31','About Batchfire','Batchfire Resources','undated','https://www.batchfire.com.au/about/','Coal products','Domestic product 4550 kcal/kg as received; export product 4500-5000 GAR.','Product specification may vary; not station invoice or realized annual quality.')
src('S32','Callide joint coal purchasing submission','ACCC public register','2006','https://www.accc.gov.au/system/files/public-registers/documents/D06%2B58398.pdf','Paragraph 12.5','Common coal bunker and bookkeeping allocation between B and C.','Historical operational arrangement, not proof that all current contract charges are identical.')
src('S33','Downer awarded Commodore contract','Downer / NZX','2018-09-05','https://www.nzx.com/announcements/323414','Contract announcement','A$286m five-year mining services contract ending August 2024.','Contract service revenue is not total station fuel cost and contract has expired.')
src('S34','Commodore project','BUMA Australia','undated','https://buma.com.au/project/commodore/','Project description','Mine exclusively supplied Millmerran; historical average 3.6Mt raw coal annually; contract ended August 2024.','Historical throughput, no verified successor contract price.')
src('S35','Queensland Coals, 14th edition','Queensland Government; Minedocs reproduction','2003','https://minedocs.com/22/Queensland_Coals-Other-2003.pdf','Table 4, PDF p.8','Historical station fuel energy: Millmerran 17.6, Tarong 19.6, Callide 19, Stanwell 26-30 GJ/t.','Old engineering reference, not contemporary assays; original parliamentary copy could not be retrieved.','PUBLICATION_REPRODUCTION')
src('S36','Loy Yang site visit webcast transcript','AGL','2018-10-23','https://www.agl.com.au/content/dam/digital/agl/documents/about-agl/investors/2018/20181023-transcript-from-webcast-loy-yang.pdf','PDF p.5, exchange at lines 206-209','Management indicated roughly A$4/t all-up coal cost.','Historical approximate verbal disclosure; question partially inaudible; cash/accounting scope not fully specified.')
src('S37','Calculation of energy costs in BRCI 2010-11','ACIL / Queensland Competition Authority','2010','https://www.qca.org.au/wp-content/uploads/2019/05/11873_ACIL-Final-Report-Calculation-of-Energy-Costs-in-the-BRCI-for-2010-11-4.pdf','Brown coal assumptions table','Loy Yang energy content 8.2GJ/t; differentiates total and variable mining cost.','Very old consultant assumptions used only as a conversion sensitivity, not current truth.')
src('S38','Loy Yang B Act 1992, Schedule 1','Victorian legislation / AustLII','1992','https://classic.austlii.edu.au/au/legis/vic/consol_act/lyba1992114/sch1.html','Coal supply agreement definition','Contract architecture includes capability and coal-consumption payments.','Historic statutory agreement description, not current price or escalation schedule.','PUBLIC_LEGISLATION_REPRODUCTION')
src('S39','Thiess awarded Yallourn mining extension','CIMIC / HOCHTIEF','2017-06-01','https://www.hochtief.com/news-media/press-releases/press-release/cimacs-thiess-awarded-195-million-yallourn-mining-extension-1','Contract announcement','RTL total revenue approximately A$450m; Thiess share A$195m; extension to 2026; includes coal, overburden and conveyors.','Partner share must not be mistaken for total contract cost; throughput and owner costs still needed.')
sources[-1]['URL']='https://www.hochtief.com/news-media/press-releases/press-release/cimics-thiess-awarded-195-million-yallourn-mining-extension-1'
src('S40','Yallourn power station and mine','CLP','undated','https://www.clpgroup.com/en/about/our-business/assets-and-services/australia/yallourn-coal-fired-power-station-and-brown-coal-open-cut-mine.html','Asset overview','Integrated brown-coal mine/power station; scheduled closure mid-2028.','No public current cost/GJ.')
src('S41','GPS Power v CS Energy [2018] QSC 294','Supreme Court of Queensland, CaseChat reproduction','2018','https://www.casechat.au/cases/au/gps-power-pty-ltd-v-cs-energy-ltd-2','IPPA clause 23 and coal arrangements','Gladstone arrangements distinguish coal supply, rail costs and contractual averaging.','Historical litigation; no single current station tariff; appeal also relevant.','INDEXED_JUDGMENT_REPRODUCTION')
src('S42','CS Energy v GPS Power [2021] QCA 194','Queensland Court of Appeal, CaseChat reproduction','2021','https://casechat.au/cases/au/cs-energy-limited-v-gps-power-pty-limited','Coal stockpile/IPPA dispute','Appellate treatment confirms need to consider contractual stockpile/accounting arrangements.','Used for commercial structure only, not a legal conclusion or current price.','INDEXED_JUDGMENT_REPRODUCTION')
src('S43','Annual Report 2025','CS Energy','2025-09-26','https://www.csenergy.com.au/ArticleDocuments/191/CS%20ENERGY%20ANNUAL%20REPORT%202025%20FULL%20COLOUR%2020250926.pdf.aspx','Fuel expense and Gladstone onerous contract notes','Group fuel expense A$172.456m; Gladstone onerous-contract provision is a different accounting item.','No station split. Provision is not annual coal expense.','PRIMARY_PDF_DOWNLOADED')
src('S44','2024 fuel price forecast report','ACIL Allen / AEMO','2025-02-25','https://aemo.com.au/-/media/files/major-publications/isp/2025/acil-allen-2024-fuel-price-forecast-report.pdf','p.33 and Appendix C','Forward modelling uses export parity/mine economics and assumes Bayswater legacy contract expiry FY2030.','Scenario forecast in real January 2024 dollars; not observed station invoices. Peabody S01 specifies 2028 for its AGL contract.')
src('S45','Consumer Price Index, June quarter 2025','ABS','2025-07-30','https://www.abs.gov.au/statistics/economy/price-indexes-and-inflation/consumer-price-index-australia/jun-quarter-2025','All groups, weighted average eight capitals','June 2025 CPI 141.7; June 2024 138.8; December 2021 121.3.','General CPI conversion, not actual coal-contract escalation.')
src('S46','Consumer Price Index, September quarter 2016','ABS','2016','https://www.abs.gov.au/ausstats/abs@.nsf/7d12b0f6763c78caca257061001cc588/7c3192fae31616f9ca2580b20076cf0f!OpenDocument','All groups, weighted average eight capitals','September 2016 index 109.4.','Quarter used as approximate transaction-era anchor.')
src('S47','Submission discussing CPI indexation','David Hardidge / Australian Treasury host','2019','https://treasury.gov.au/sites/default/files/2019-04/c2019-t342318-david_hardidge.pdf','Historical CPI series','September 2018 index 113.5.','Third-party submission on official host; standard CPI input, not a coal-cost source.','PUBLIC_SECONDARY_DOCUMENT')

S={s['SOURCE_ID']:s for s in sources}
rows=[]
def row(plant,state,old,base,lo,hi,beta,new,nlo,nhi,method,conf,regime,ids,note,anchor=None):
    rows.append(dict(PLANT=plant,STATE=state,CURRENT_V06_AUD_GJ=old,ORIGINAL_BASE_AUD_GJ=base,ORIGINAL_LOW_AUD_GJ=lo,ORIGINAL_HIGH_AUD_GJ=hi,BASE_AUD_GJ=new,LOW_AUD_GJ=nlo,HIGH_AUD_GJ=nhi,CHANGE_AUD_GJ=None if base is None else round(new-base,4),PRICE_SOURCE_TYPE=method,CONFIDENCE=conf,PRODUCTION_STATUS='INACTIVE' if plant=='Liddell' else 'ACTIVE_ASSET_NOT_LIVE_AVAILABILITY',MODEL_INPUT_STATUS='EXCLUDE_CLOSED' if plant=='Liddell' else 'PROVISIONAL_ANALYST_ASSUMPTION',PRICE_BASIS='DELIVERED_STATION_AVERAGE_FUEL_COST_TARGET',REAL_BASE_DATE='2025-06-30',EVIDENCE_CUTOFF='2026-09-15',ASSUMPTION_HORIZON='NEAR_TERM_USING_LATEST_KNOWN_REGIME',SUPPLY_REGIME=regime,ORIGINAL_GROSS_BETA_REFERENCE=beta,VERIFIED_EXPORT_PRICE_WEIGHT=None,CURRENT_PUBLIC_STATION_PRICE_AUD_GJ=None,HISTORICAL_OR_PROXY_ANCHOR_AUD_GJ=anchor,SELECTION_METHOD=method,SOURCE_IDS=';'.join(ids),SOURCE_URL=' | '.join(S[i]['URL'] for i in ids),NOTES=note,RANGE_TYPE='ANALYST_SCENARIO_NOT_STATISTICAL_CONFIDENCE_INTERVAL'))

row('Bayswater','NSW',4.1241,3.6,3.2,4.1241,.6375,3.6,3.2,5.5,'RETAIN_PRIOR_FLEET_CONSTRAINED','LOW','Wilpinjong legacy open-book plus other contracted Hunter supply',['S01','S02','S03','S04'],'Retain 3.60 as provisional prior; fleet reconciliation cannot identify station price. Increase high to 5.50 for contract roll-off and higher recent cost. Wilpinjong contract ends 2028, not universal FY2030. Current mine and export-linked energy weights unavailable.')
row('Eraring','NSW',7.0161,5.5,4.5,7.0161,.325,5.5,4.5,8,'RETAIN_PRIOR_CONTRACT_PRICE_UNKNOWN','LOW','Myuna captive-to-customer plus Mandalong/other suppliers; discounted index contracts and hedges',['S05','S06','S07','S08','S09'],'No disclosed station invoice validates 5.50. Retain as provisional; broaden upper case. Do not treat proposed A$50m/year Myuna premium as final agreed price. FY27 75-85% coverage implies 15-25% uncovered volume, not export blend or price beta.')
row('Mt Piper','NSW',7.2197,5,4,7.2197,.325,7.5,5.5,8.5,'SUPPLIER_DOMESTIC_ASP_PROXY','LOW','Centennial multi-mine Springvale/Airly supply; confidential domestic contracts',['S10','S11','S12','S13','S14','S15','S16'],'Raise provisional base to 7.50. Supplier 2024 domestic ASP170.52/t rebased using June2024 CPI proxy and assumed23GJ/t gives7.57/GJ, rounded to nearest0.50. Supplier average is not station delivered invoice. Latest mixed ASPs support a lower downside; station blend, freight and actual assay remain unknown.',170.52*141.7/138.8/23)
row('Vales Point B','NSW',7.0161,5,4.3,5.8,.4,5,4,7.5,'RETAIN_PRIOR_BLEND_COMPONENTS_UNKNOWN','LOW','Approximately half Chain Valley; remaining external domestic supply',['S17','S18','S19','S09'],'Retain5.00; broaden range. Approximate50% is a tonne share, not verified energy weight. Original3.50 captive/6.50 external prices are unverified and removed from reviewed component fields. Chain Valley coal restricted to Vales Point; external share is not automatically export-indexed.')
row('Stanwell PS','QLD',4.9591,2.55,2.2,3.1,.125,2.55,2.2,4.5,'RETAIN_PRIOR_LEGACY_CSA_WITH_RESET_RISK','LOW','Curragh domestic CSA; amendments, prepayments and rebate changes',['S20','S21','S22','S35'],'Retain2.55 only as legacy-price prior; increase high for altered economics. 2025/26 changes invalidate a timeless fixed-price description. Do not divide financing advances by current burn and call the result current fuel expense; current tariff reconciliation unresolved.')
for name in ['Tarong','Tarong North']:
    row(name,'QLD',3.8594,2.55,2,3,.069,2.55,2,3.5,'RETAIN_PRIOR_CONTRACTOR_COST_CROSSCHECK','LOW_MEDIUM','Owned Meandu mine and conveyor',['S23','S24','S25','S35'],'Retain2.55. New750m/5.5year service contract is only part of cost; 100% client-owned fleet. Capacity7.6Mt is not actual output. Same coal price/GJ for Tarong and Tarong North; heat rate belongs in consumption conversion. Export weight0 is a near-term captive-supply modelling assumption.')
row('Kogan Creek','QLD',2.3217,1.7,1.5,2,.0975,1.7,1.2,2.2,'RETAIN_PRIOR_PARTIAL_MINING_COST_ANCHOR','LOW_MEDIUM','Owned Kogan Creek mine and conveyor',['S26','S27','S28'],'Retain1.70 with lower downside;150m/4year contractor cost is partial, not all-in owner fuel cost. Contract endedJune2026 with option; extension pricing not verified. Zero near-term export pass-through is a captive-supply assumption, not a measured statistical beta.')
for name in ['Callide B','Callide C']:
    row(name,'QLD',3.3197,2,1.7,2.5,.505,2,1.4,2.5,'RETAIN_PRIOR_HISTORICAL_CONTRACT_CROSSCHECK','LOW_MEDIUM','Batchfire Callide domestic priority contract; common mine system',['S29','S30','S31','S32','S28'],'Retain2.00. Historical2016 approx27/t escalated by general CPI and divided by4550kcal/kg gives1.84/GJ; this is a crosscheck, not actual contract escalation. Court passage available via indexed reproduction only. Supplier exports do not establish domestic contract index exposure. Equal B/C price remains a simplifying assumption.',27*141.7/109.4/(4550*.004184))
row('Loy Yang A','VIC',.8656,.68,.55,.8656,0,.68,.55,.95,'RETAIN_PRIOR_DIRECT_HISTORICAL_MINE_ANCHOR','LOW_MEDIUM','Owned brown-coal mine and conveyor',['S36','S37','S03','S45','S47'],'Retain0.68;2018 management roughly4/t becomes0.61/GJ under CPI conversion and historical8.2GJ/t quality. Cost scope and current assay uncertain; upper range broadened. Fleet average is only a crosscheck. No conventional thermal-export blend.',4*141.7/113.5/8.2)
row('Loy Yang B','VIC',.8656,.72,.55,.8656,0,.72,.55,1.1,'RETAIN_PRIOR_SAME_MINE_CSA_UNKNOWN','LOW','Loy Yang mine supplied under separate CSA',['S38','S36','S37'],'Retain0.72 as contract-price proxy only. Difference from Loy Yang A is an unverified allowance, not disclosed seller margin. Heat-rate difference cannot justify a different price/GJ. Current capability/volume charges and allocation unavailable. No conventional export blend.')
row('Yallourn','VIC',.8656,.8656,.65,1,0,.8656,.65,1.2,'RETAIN_PRIOR_NO_CURRENT_UNIT_COST','LOW','Integrated brown-coal mine and conveyor',['S39','S40'],'Retain0.8656 solely as prior; four decimals do not imply accuracy. Historical RTL contract450m total,195m Thiess share: neither is all-in coal cost. No current public unit price established. No conventional export blend.')
row('Gladstone','QLD',None,3.8594,3,5.5,.505,3.8594,3,6.5,'RETAIN_PRIOR_IPPA_COST_UNKNOWN','VERY_LOW','Rail-delivered coal; IPPA/tolling and distinct allocation arrangements',['S41','S42','S43'],'Retain3.8594 as explicitly unvalidated placeholder; source was peer transfer. Widen high for rail and contract uncertainty. IPPA provisions and group fuel expense cannot determine station price. Actual supplier allocation and benchmark weight unknown.')
row('Millmerran','QLD',None,2.05,1.6,2.7,0,2.05,1.2,2.7,'RETAIN_PRIOR_HISTORICAL_SERVICE_COST_CROSSCHECK','LOW','Commodore captive mine and conveyor',['S33','S34','S35','S45','S47'],'Retain2.05 as conservative provisional total cost. Historical286m/5years/3.6Mt/17.6GJ/t rebased by CPI gives1.13/GJ contractor component; excludes owner costs and successor contract. Do not equate contractor fee with total fuel cost. Zero export pass-through is near-term mine-mouth assumption.',286/5/3.6/17.6*141.7/113.5)
row('Liddell','NSW',None,None,None,None,0,None,None,None,'CLOSED_EXCLUDE','NOT_APPLICABLE','Closed April2023',['S01'],'Closed asset retained for history. Fuel prices blank; do not interpret as zero-cost active generation.')

def write_csv(name,data):
    with (OUT/name).open('w',newline='',encoding='utf-8-sig') as f:
        w=csv.DictWriter(f,fieldnames=list(data[0]));w.writeheader();w.writerows(data)

blends=[]
def blend(plant,component,share,basis,domestic,indexed,physical,weight,wstatus,ids,notes,coveredlo=None,coveredhi=None):
    blends.append(dict(PLANT=plant,COMPONENT=component,PHYSICAL_SUPPLY_SHARE=share,SHARE_BASIS=basis,SHARE_PERIOD='LATEST_PUBLIC_DESCRIPTION_NOT_METERED_CURRENT_YEAR',DOMESTIC_SUPPLY=domestic,CONTRACT_EXPORT_INDEXATION=indexed,PHYSICAL_EXPORT_DIVERTIBILITY=physical,RECOMMENDED_NEAR_TERM_EXPORT_WEIGHT=weight,WEIGHT_STATUS=wstatus,VERIFIED_EXPORT_BLEND_WEIGHT=None,FY27_CONTRACTED_HEDGED_STOCK_COVERAGE_LOW=coveredlo,FY27_CONTRACTED_HEDGED_STOCK_COVERAGE_HIGH=coveredhi,COMPONENT_PRICE_AUD_GJ=None,SOURCE_IDS=';'.join(ids),SOURCE_URL=' | '.join(S[i]['URL'] for i in ids),NOTES=notes))
blend('Bayswater','Wilpinjong plus other Hunter mines',None,'UNKNOWN_CURRENT_ENERGY_OR_TONNES','YES','MIXED_UNDISCLOSED','SUPPLIER_EXPORTS_BUT_CONTRACT_RESTRICTED',None,'UNKNOWN',['S01','S02'],'Historical7Mtpa Wilpinjong nomination cannot be used as current Bayswater share after Liddell closure. Original beta0.6375 unverified.')
blend('Eraring','All coal incl Myuna/Mandalong/other',None,'UNKNOWN_MINE_MIX','YES','LARGELY_DISCOUNTED_NEWCASTLE_6000_WITH_HEDGES','MIXED',None,'UNKNOWN',['S05','S06','S08'],'FY27 residual uncovered volume15-25% is an arithmetic complement of coverage, not physical export blend or effective beta. Do not use0.325 as a verified weight.',.75,.85)
blend('Eraring','Myuna subset',None,'UNKNOWN','YES','FINAL_FORMULA_NOT_DISCLOSED','LANDLOCKED_EXCLUSIVE_CUSTOMER',None,'UNKNOWN',['S06','S08'],'Myuna share not disclosed; exclusive physical supply does not prove that negotiated price never reflects market alternatives.')
blend('Mt Piper','Springvale/Airly multi-mine',None,'UNKNOWN','YES','CONFIDENTIAL_DOMESTIC_CONTRACT','WESTERN_SYSTEM_HAS_EXPORT_ROUTE',None,'UNKNOWN',['S10','S11'],'No defensible current mine or benchmark weights. Supplier-wide export sales share would be the wrong denominator.')
blend('Vales Point B','Chain Valley / Mannering',.5,'APPROXIMATE_TONNES','YES','UNKNOWN','NO_UNDER_2026_CONSENT',None,'PHYSICAL_RESTRICTION; INDEXATION_NOT_PROVEN',['S17','S18'],'50% is approximate tonnes. Physical export diversion is restricted; negotiated price sensitivity remains unknown and is left blank. Component price unknown.')
blend('Vales Point B','External domestic coal',.5,'RESIDUAL_APPROXIMATE_TONNES','YES','UNKNOWN','DEPENDS_ON_MINE_AND_CONTRACT',None,'UNKNOWN',['S17','S09'],'Residual50% external is not50% export-priced. Convert tonne weights with actual calorific values before using AUD/GJ blends.')
blend('Stanwell PS','Curragh domestic CSA',None,'CURRENT_VOLUME_SHARE_NOT_DISCLOSED','YES','AMENDED_CONTRACT_NOT_SIMPLE_SPOT_LINK','CONTRACTUAL_PRIORITY_AND_SUPPLIER_EXPORTS',None,'UNKNOWN_AFTER_AMENDMENTS',['S20','S21','S22'],'Coronado thermal33% of Australian sales is not station export share. Original0.125 unverified.')
for plant in ['Tarong','Tarong North','Kogan Creek','Millmerran','Loy Yang A','Loy Yang B','Yallourn']:
    ids={'Tarong':['S23'],'Tarong North':['S23'],'Kogan Creek':['S27','S28'],'Millmerran':['S34'],'Loy Yang A':['S36'],'Loy Yang B':['S38','S44'],'Yallourn':['S40']}[plant]
    brown=plant in ['Loy Yang A','Loy Yang B','Yallourn']
    blend(plant,'Captive or dedicated mine system',1,'NORMAL_SUPPLY_REGIME_NOT_ANNUAL_METERED_MIX','YES','NO_CONVENTIONAL_EXPORT_LINK_MODELLED','NO_CONVENTIONAL_EXPORT_PRODUCT' if brown else 'NO_ROUTINE_DIVERSION_MODELLED',0,'RECOMMENDED_MODELLING_ASSUMPTION',['S'+i[1:] for i in ids],'100% describes normal dedicated source, not guaranteed annual actual mix. Zero export weight is a model recommendation; mine inflation, royalties, owner costs and contract resets can still change price.')
for plant in ['Callide B','Callide C']:
    blend(plant,'Callide Mine domestic CSA',1,'NORMAL_SUPPLY_REGIME_NOT_METERED_MIX','YES','HISTORICALLY_NON_MARKET_LINKED','SUPPLIER_EXPORTS_BUT_DOMESTIC_OBLIGATIONS_FIRST',0,'CONDITIONAL_ON_CSA_CONTINUITY',['S28','S29','S31'],'Zero spot-export pass-through scenario requires continuing domestic CSA terms. Original0.505 not verified. Supplier export capability is real but does not override domestic contractual priority.')
blend('Gladstone','IPPA coal pool',None,'UNKNOWN','YES','UNKNOWN','DEPENDS_ON_SUPPLY_AND_IPPA',None,'UNKNOWN',['S41','S42','S43'],'No defensible export weight; original0.505 remains only an archived input. No Newcastle4500/5500/6000 mix established.')

calc=[]
def c(i,plant,label,formula,val,unit,ids,assumption):
    calc.append(dict(CALC_ID=i,PLANT=plant,CALCULATION=label,FORMULA_TEXT=formula,RESULT=val,UNIT=unit,SOURCE_IDS=';'.join(ids),ASSUMPTIONS_AND_LIMITATIONS=assumption))
c('C01','Mt Piper','Domestic supplier proxy in June2025 money','170.52 * (141.7 / 138.8) / 23',170.52*141.7/138.8/23,'AUD_JUN2025_PER_GJ',['S11','S45'],'23GJ/t is analyst assumption, not measured Mt Piper quality. June2024 CPI approximates full-year2024 price timing. Freight and mine mix unobserved. Base rounded to nearest0.50.')
c('C02','Mt Piper','Same proxy at24GJ/t','170.52 * (141.7 / 138.8) / 24',170.52*141.7/138.8/24,'AUD_JUN2025_PER_GJ',['S11','S45'],'Quality-only sensitivity; not low end of full uncertainty range.')
c('C03','Mt Piper','Same proxy at21GJ/t','170.52 * (141.7 / 138.8) / 21',170.52*141.7/138.8/21,'AUD_JUN2025_PER_GJ',['S11','S45'],'Quality-only sensitivity; not a station assay.')
c('C04','Callide B; Callide C','Domestic product energy conversion','4550 * 0.004184',4550*.004184,'GJ_PER_TONNE',['S31'],'Thermochemical kcal conversion; as-received stated product.')
c('C05','Callide B; Callide C','Historical domestic price CPI crosscheck','27 * (141.7 / 109.4) / (4550 * 0.004184)',27*141.7/109.4/(4550*.004184),'AUD_JUN2025_PER_GJ',['S29','S31','S45','S46'],'General CPI scenario, not verified contract escalation; approx2016 price, approximate source quarter; historical court text access limitation. Retained base2.00 is not mechanically replaced by this result.')
c('C06','Loy Yang A','Historical management cost CPI crosscheck','4 * (141.7 / 113.5) / 8.2',4*141.7/113.5/8.2,'AUD_JUN2025_PER_GJ',['S36','S37','S45','S47'],'8.2GJ/t old consultant assumption; quarter proxied Sep2018 for Oct2018 remark; all-up cost scope unclear.')
c('C07','Millmerran','Historical mining-services-only cost','286 / 5 / 3.6 / 17.6 * (141.7 / 113.5)',286/5/3.6/17.6*141.7/113.5,'AUD_JUN2025_PER_GJ',['S33','S34','S35','S45','S47'],'Uses A$m and Mt cancelling. Contract headline divided equally by years and historical output. Owner costs absent. CPI treats award value as2018 money although multiyear nominal escalation unknown; diagnostic only.')
c('C08','Kogan Creek','Historical contractor-only annual fee per tonne','150 / 4 / 2.5',150/4/2.5,'AUD_PER_TONNE_HEADLINE_CONTRACT_BASIS',['S26'],'2.5Mt/year is analyst throughput scenario. Nominal contract headline basis; not delivered current total. No unverified coal-quality conversion applied.')
c('C09','Tarong; Tarong North','New contractor fee at6Mt/year','750 / 5.5 / 6 / 19.6',750/5.5/6/19.6,'AUD_PER_GJ_FORWARD_CONTRACT_HEADLINE_BASIS',['S24','S25','S35'],'6Mt/year analyst scenario; 19.6GJ/t historical reference. Not converted to June2025 due unknown expenditure schedule. Owner-owned fleet and other costs excluded.')
c('C10','Tarong; Tarong North','Contractor fee at rated capacity','750 / 5.5 / 7.6 / 19.6',750/5.5/7.6/19.6,'AUD_PER_GJ_FORWARD_CONTRACT_HEADLINE_BASIS',['S23','S24','S35'],'Capacity sensitivity only, not actual production or an all-in delivered price.')
c('C11','Eraring','FY27 uncovered volume low','1 - 0.85',.15,'FRACTION_OF_CONSUMED_VOLUME',['S05'],'Not export blend, physical mine share, or effective price beta.')
c('C12','Eraring','FY27 uncovered volume high','1 - 0.75',.25,'FRACTION_OF_CONSUMED_VOLUME',['S05'],'Coverage forecast asApr2026; not currentSept2026 audited coverage.')
c('C13','Vales Point B','Original screenshot blend arithmetic only','0.5 * 3.5 + 0.5 * 6.5',5,'AUD_PER_GJ_IF_ENERGY_WEIGHTS_EQUAL',['S17'],'Component prices3.5 and6.5 are UNSOURCED screenshot inputs.50% public share is tonnes; formula only valid if energy shares also50%. Not used as validated price evidence.')

write_csv('nem_coal_prices_reviewed.csv',rows)
write_csv('nem_coal_export_blends.csv',blends)
write_csv('coal_source_register.csv',sources)
write_csv('coal_calculations.csv',calc)
(OUT/'research_data.json').write_text(json.dumps(dict(prices=rows,blends=blends,sources=sources,calculations=calc),indent=2),encoding='utf-8')
print(f'Created {len(rows)} price rows, {len(blends)} supply rows, {len(sources)} sources, {len(calc)} calculations.')

report_path=OUT/'coal_price_research_report.md'
report=report_path.read_text(encoding='utf-8').split('\n<!-- GENERATED SOURCE LIST -->')[0]
report+='\n<!-- GENERATED SOURCE LIST -->\n\n'
for s in sources:
    report+=f"{int(s['SOURCE_ID'][1:])}. {s['PUBLISHER']}. [{s['TITLE']}]({s['URL']}). {s['PUBLICATION_DATE']}. {s['LOCATOR']}. Access: {s['ACCESS_STATUS']}.\n\n"
report_path.write_text(report,encoding='utf-8')

assert len(rows)==16 and len({r['PLANT'] for r in rows})==16
for r in rows:
    if r['PLANT']=='Liddell':
        assert all(r[k] is None for k in ['BASE_AUD_GJ','LOW_AUD_GJ','HIGH_AUD_GJ'])
    else:
        assert 0<r['LOW_AUD_GJ']<=r['BASE_AUD_GJ']<=r['HIGH_AUD_GJ']
    assert all(i in S for i in r['SOURCE_IDS'].split(';'))
    assert r['CURRENT_PUBLIC_STATION_PRICE_AUD_GJ'] is None
for b in blends:
    assert b['PHYSICAL_SUPPLY_SHARE'] is None or 0<=b['PHYSICAL_SUPPLY_SHARE']<=1
    assert b['RECOMMENDED_NEAR_TERM_EXPORT_WEIGHT'] is None or 0<=b['RECOMMENDED_NEAR_TERM_EXPORT_WEIGHT']<=1
    assert all(i in S for i in b['SOURCE_IDS'].split(';'))
assert sum(b['PHYSICAL_SUPPLY_SHARE'] for b in blends if b['PLANT']=='Vales Point B')==1
for filename,expected in [('nem_coal_prices_reviewed.csv',16),('nem_coal_export_blends.csv',17),('coal_source_register.csv',47),('coal_calculations.csv',13)]:
    with (OUT/filename).open(encoding='utf-8-sig',newline='') as f:
        loaded=list(csv.DictReader(f))
    assert len(loaded)==expected and all(None not in x for x in loaded)
    assert not any(str(v).startswith(('=','+','@')) for x in loaded for v in x.values())
print('Validated CSV round trips, row uniqueness, ordered bounds, source references, blank prices and blend shares.')

files=['nem_coal_prices_reviewed.csv','nem_coal_export_blends.csv','coal_source_register.csv','coal_calculations.csv','coal_price_research_report.md','README.md']
if all((OUT/f).exists() for f in files):
    with zipfile.ZipFile(OUT/'nem_coal_research_package.zip','w',zipfile.ZIP_DEFLATED) as z:
        for f in files:z.write(OUT/f,f)
    print('Packaged six deliverables in nem_coal_research_package.zip')
